### PR TITLE
Add reusable workflow to add release notes to the docs

### PR DESCRIPTION
**Pull request by BennyDeBock**
This workflow gathers information about the release and adds it to the documentation. After that, it creates a new branch with a pull request on the docs repo

### CODE REVIEW

**Review by 0xTim — CHANGES_REQUESTED** [review]
Can you add the `no-translation-needed` to the PR? That stops us creating an issue for every release note

**Comment by BennyDeBock** [comment]
> Can you add the `no-translation-needed` to the PR? That stops us creating an issue for every release note

Yeah. It was something i thought off but forgot later 😅. Once that is done I'll let you know

**Comment by BennyDeBock** [comment]
@0xTim Should be good to go now

**Review by 0xTim — APPROVED** [review]
Thanks!

**Comment by 0xTim** [comment]
@BennyDeBock do you reckon you could sign the commits?

**Comment by BennyDeBock** [comment]
I'd have to do that when I'm at home. I forgot i needed to do that for this repo 😅

**Comment by 0xTim** [comment]
@BennyDeBock You still planning on signing the commits?

**Comment by BennyDeBock** [comment]
Yes i am. I'll look into doing that this weekend. I've just been absolutely swamped lately 😅

**Comment by 0xTim** [comment]
Make sure you enjoy Xmas!

**Comment by 0xTim** [comment]
@BennyDeBock ping 😅

**Pull request closed without merging**
